- name: Install nginx
  hosts: all
  become: true
  vars:
    nginx_user: nginx
    nginx_home: /home/nginx
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - podman
          - systemd-container
        state: present
        update_cache: true
        cache_valid_time: 3600
      tags: packages
    - name: Create user
      ansible.builtin.user:
        name: "{{ nginx_user }}"
        state: present
        create_home: true
        home: "{{ nginx_home }}"
        shell: /sbin/nologin
        system: true
      tags: user
    - name: Allocate user ids
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: "{{ nginx_user }}:100000:65536"
        create: true
      tags: user
    - name: Allocate group ids
      ansible.builtin.lineinfile:
        path: /etc/subgid
        line: "{{ nginx_user }}:100000:65536"
        create: true
      tags: user
    - name: Enable lingering
      ansible.builtin.command:
        cmd: "loginctl enable-linger {{ nginx_user }}"
      changed_when: false
      tags: user
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        mode: '0755'
      loop:
        - "{{ nginx_home }}/.config/containers/systemd"
        - "{{ nginx_home }}/nginx/content"
      tags: config
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        mode: '0644'
      loop:
        - src: ~/nginx/nginx.conf
          dest: "{{ nginx_home }}/nginx/nginx.conf"
        - src: ~/nginx/content/index.html
          dest: "{{ nginx_home }}/nginx/content/index.html"
        - src: ~/.config/containers/systemd/nginx.container
          dest: "{{ nginx_home }}/.config/containers/systemd/nginx.container"
      tags: config
    - name: Reload daemons
      ansible.builtin.command:
        cmd: "systemctl --machine={{ nginx_user }}@ --user daemon-reload"
      changed_when: false
      tags: service
    - name: Start service
      ansible.builtin.command:
        cmd: "systemctl --machine={{ nginx_user }}@ --user start nginx"
      changed_when: false
      tags: service
